FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=db_name
ENV MYSQL_USER=db_user
ENV MYSQL_PASSWORD=db_password

COPY ./scripts/init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306
